order:
  billing:
    name: "Abcde"
    address:
      name: "7/6, August Kranti Marg"
      building: "Siri Fort Institutional"
      locality: "Siri Fort Institutional Area, Siri Fort"
      city: "New Delhi"
      state: "Delhi"
      country: "India"
      area_code: "110049"
    tax_number: "29AAACU1901H1ZK"
    phone: "9999999999"
    email: "abc@gmail.com"
    created_at: "2024-12-12T09:07:07.986Z"
    updated_at: "2024-12-12T09:07:07.986Z"
  fulfillments:
    - id: "b849dfdd-4c6b-4eac-a9c7-709ec509a7a4"
      type: "Delivery"
      end:
        contact:
          phone: "9999999999"
          email: "nobody@nomail.com"
        location:
          address:
            area_code: "122503"
            building: "Siri Fort Institutional"
            city: "Gurgaon"
            country: "IND"
            locality: "Siri Fort Institutional Area, Siri Fort"
            name: "abc"
            state: "Haryana"
          gps: "28.326451046477988,76.77823101205861"
  items:
    - fulfillment_id: "b849dfdd-4c6b-4eac-a9c7-709ec509a7a4"
      id: "5041C0537916A32DBB468566368C246C_44241145561347_default"
      quantity:
        count: "1"
    - id: "5041C0537916A32DBB468566368C246C_44241145659651_default"
      fulfillment_id: "b849dfdd-4c6b-4eac-a9c7-709ec509a7a4"
      quantity:
        count: "2"
  provider:
    id: "sellerNP.com"
    locations:
      - id: "69b685813a63a8114c7c40e4b17dd08c"
  payment:
    type: "ON-FULFILLMENT"
