codes:
  - code: 100
    action_id: search
    action: search
    default: search/default.yaml
    message_id: true
  - code: 101
    action_id: on_search
    action: on_search
    default: on_search/default.yaml
    message_id: false
  - code: 102
    action_id: search_1
    action: search
    default: search/search_1/default.yaml
    message_id: true
  - code: 103
    action_id: on_search_1
    action: on_search
    default: on_search/on_search_1/default.yaml
    message_id: false
  - code: 104
    action_id: on_search_2
    action: on_search
    default: on_search/on_search_2/default.yaml
    message_id: true
  - code: 105
    action_id: select
    action: select
    default: select/default.yaml
    message_id: true
  - code: 106
    action_id: on_select
    action: on_select
    default: on_select/default.yaml
    message_id: false
  - code: 107
    action_id: init
    action: init
    default: init/default.yaml
    message_id: true
  - code: 108
    action_id: on_init
    action: on_init
    default: on_init/default.yaml
    message_id: false
  - code: 109
    action_id: confirm
    action: confirm
    default: confirm/default.yaml
    message_id: true
  - code: 110
    action_id: on_confirm
    action: on_confirm
    default: on_confirm/default.yaml
    message_id: false
  - code: 111
    action_id: on_status_pending
    action: on_status
    default: on_status/default.yaml
    message_id: true
  - code: 112
    action_id: on_status_agent_assigned
    action: on_status
    default: on_status/default.yaml
    message_id: true
  - code: 113
    action_id: on_status_at_pickup
    action: on_status
    default: on_status/default.yaml
    message_id: true
  - code: 114
    action_id: on_status_order_picked
    action: on_status
    default: on_status/default.yaml
    message_id: true
  - code: 115
    action_id: on_status_at_delivery
    action: on_status
    default: on_status/default.yaml
    message_id: true
  - code: 116
    action_id: on_status_order_delivered
    action: on_status
    default: on_status/default.yaml
    message_id: true
  - code: 117
    action_id: on_status_packed
    action: on_status
    default: on_status/default.yaml
    message_id: true
  - code: 118
    action_id: select_oos
    action: select
    default: select/default.yaml
    message_id: true
  - code: 119
    action_id: on_select_oos
    action: on_select
    default: on_select/on_select_oos/default.yaml
    message_id: false
  - code: 120
    action_id: cancel
    action: cancel
    default: cancel/default.yaml
    message_id: true
  - code: 121
    action_id: on_cancel
    action: on_cancel
    default: on_cancel/default.yaml
    message_id: false
  - code: 120
    action_id: cancel_force
    action: cancel
    default: cancel/cancel_force/default.yaml
    message_id: true
  - code: 121
    action_id: on_select_multiple_fulfillment
    action: on_select
    default: on_select/on_select_multiple_fulfillment/default.yaml
    message_id: false
  - code: 122
    action_id: track
    action: track
    default: track/default.yaml
    message_id: true
  - code: 123
    action_id: on_track
    action: on_track
    default: on_track/default.yaml
    message_id: false
  - code: 124
    action_id: init_fulfillment_array
    action: init
    default: init/init_fulfillment_array/default.yaml
    message_id: true
  - code: 125
    action_id: on_init_fulfillment_array
    action: on_init
    default: on_init/on_init_fulfillment_array/default.yaml
    message_id: false
  - code: 126
    action_id: on_select_fulfillment_array
    action: on_select
    default: on_select/on_select_fulfillment_array/default.yaml
    message_id: false
  - code: 127
    action_id: update_address
    action: update
    default: update/update_address/default.yaml
    message_id: true
  - code: 128
    action_id: update_buyer_inst
    action: update
    default: update/update_buyer_inst/default.yaml
    message_id: true
  - code: 129
    action_id: on_update_address
    action: on_update
    default: on_update/default.yaml
    message_id: false
  - code: 130
    action_id: on_update_buyer_inst
    action: on_update
    default: on_update/default.yaml
    message_id: false
  - code: 131
    action_id: on_update_delivery_auth
    action: on_update
    default: on_update/default.yaml
    message_id: true
  - code: 132
    action_id: init_multiple_fulfillment
    action: init
    default: init/init_multiple_fulfillment/default.yaml
    message_id: true
  - code: 133
    action_id: on_status_self_delivery_picked
    action: on_status
    default: on_status/default.yaml
    message_id: true
