order:
  provider:
    id: P1
    locations:
      - id: L1
  items:
    - id: I1
      quantity:
        count: 1
      location_id: L1
      fulfillment_id: F1
  billing:
    address:
      building: my building name or house
      city: Mumbai
      state: Maharashtra
      country: IND
      area_code: "400053"
      locality: my street name
      name: my house or door or floor
    phone: "9898989898"
    name: ONDC buyer
    email: nobody@nomail.com
    created_at: "2024-12-23T07:01:43.145Z"
    updated_at: "2024-12-23T07:01:43.145Z"
  fulfillments:
    - id: F1
      type: Delivery
      end:
        contact:
          email: nobody@nomail.com
          phone: "9898989898"
        location:
          gps: 19.131140,72.834091
          address:
            building: mock-building
            city: mock-city
            state: mock-state
            country: IND
            area_code: "400053"
            locality: mock-locality
            name: mock-house-name
