save-data:
  message_id: "$.context.message_id"
  items: "$.message.order.items[*]"
  provider: "$.message.order.provider"
  select_fulfillment: "$.message.order.fulfillments[*]"
  city_code: "$.context.city"
  offers: "$.message.order.offers[*]"
