save-data:
  message_id: "$.context.message_id"
  is_ready_to_ship: $.message.order.fulfillments[*].tags[?(@.code=="state")].list[?(@.code=="ready_to_ship")].value
  update_fulfillments: "$.message.order.fulfillments[*]"
