order:
  provider:
    id: P1
    locations:
      - id: L1
  items:
    - id: I1
      quantity:
        count: 1
      fulfillment_id: F1
  billing:
    address:
      building: my building name or house
      city: Mumbai
      state: Maharashtra
      country: IND
      area_code: "400053"
      locality: my street name
      name: my house or door or floor
    phone: "9898989898"
    name: ONDC buyer
    email: nobody@nomail.com
    created_at: "2024-12-23T07:01:43.145Z"
    updated_at: "2024-12-23T07:01:43.145Z"
  fulfillments:
    - id: F1
      type: Delivery
      end:
        contact:
          email: nobody@nomail.com
          phone: "9898989898"
        location:
          gps: 19.131140,72.834091
          address:
            building: my building name or house
            city: Mumbai
            state: Maharashtra
            country: IND
            area_code: "400053"
            locality: my street name
            name: my house or door or floor
      tracking: true
  quote:
    price:
      value: "100"
      currency: INR
    breakup:
      - "@ondc/org/item_id": I1
        "@ondc/org/item_quantity":
          count: 1
        title: Plain Atta
        "@ondc/org/title_type": item
        price:
          currency: INR
          value: "100.00"
        item:
          price:
            currency: INR
            value: "100.00"
      - "@ondc/org/item_id": I1
        title: Delivery charges
        "@ondc/org/title_type": delivery
        price:
          currency: INR
          value: "00.00"
      - "@ondc/org/item_id": I1
        title: Convenience Fee
        "@ondc/org/title_type": misc
        price:
          currency: INR
          value: "00.00"
    ttl: P1D
  payment:
    "@ondc/org/buyer_app_finder_fee_type": percent
    "@ondc/org/buyer_app_finder_fee_amount": "3"
    "@ondc/org/settlement_details":
      - settlement_counterparty: seller-app
        settlement_phase: sale-amount
        settlement_type: neft
        beneficiary_name: xxxx
        settlement_bank_account_no: XXXX
        settlement_ifsc_code: XXXX
        bank_name: XXXX
        branch_name: XXXX
  tags:
    - code: bpp_terms
      list:
        - code: np_type
          value: MSN
        - code: tax_number
          value: 00ABCCH7409R1ZZ
        - code: provider_tax_number
          value: ABCDE1234F
