update_target: item
order:
  id: 2025-02-10-293522
  fulfillments:
    - type: Return
      id: ad392135
      tags:
        - code: return_request
          list:
            - code: id
              value: 67a9ad8173aa689a957eaf54
            - code: item_id
              value: oc_72
            - code: item_quantity
              value: "1"
            - code: reason_id
              value: "001"
            - code: reason_desc
              value: the product is damaged
            - code: images
              value: https://reference-buyer-app-assets.s3-ap-south-1.amazonaws.com/public-assets/2025-02-10-293522/9d13d0d3-6b21-405e-bfc0-b014485adaa2.png
            - code: ttl_approval
              value: PT24H
            - code: ttl_reverseqc
              value: P3D
