message:
  update_target: item
  order:
    id: O1
    fulfillments:
      - type: Return
        tags:
          - code: return_request
            list:
              - code: id
                value: R1
              - code: item_id
                value: I1
              - code: parent_item_id
                value: DI1
              - code: item_quantity
                value: "1"
              - code: reason_id
                value: "003"
              - code: reason_desc
                value: detailed description for return
              - code: images
                value: "url_for_image1,url_for_image2"
              - code: ttl_approval
                value: PT24H
              - code: ttl_reverseqc
                value: P3D
