codes:
  - code: 100
    default: GROCERY/1.2.5/search/search/default.yaml
    action_id: search
    action: search
    message_id: true
  - code: 101
    default: GROCERY/1.2.5/on_search/on_search/default.yaml
    action_id: on_search
    action: on_search
    message_id: false
  - code: 102
    default: GROCERY/1.2.5/search/search_inc/default.yaml
    action_id: search_inc
    action: search
    message_id: true
  - code: 902
    default: GROCERY/1.2.5/on_search/on_search_inc_disable/default.yaml
    action_id: on_search_inc_disable
    action: on_search
    message_id: true
  - code: 103
    default: GROCERY/1.2.5/on_search/on_search_inc/default.yaml
    action_id: on_search_inc
    action: on_search
    message_id: true
  - code: 104
    default: GROCERY/1.2.5/on_search/on_search_104/default.yaml
    action_id: on_search_104
    action: on_search
    message_id: false
  - code: 105
    default: GROCERY/1.2.5/select/select/default.yaml
    action_id: select
    action: select
    message_id: true
  - code: 106
    default: GROCERY/1.2.5/on_select/on_select/default.yaml
    action_id: on_select
    action: on_select
    message_id: false
  - code: 107
    default: GROCERY/1.2.5/init/init/default.yaml
    action_id: init
    action: init
    message_id: true
  - code: 108
    default: GROCERY/1.2.5/on_init/on_init/default.yaml
    action_id: on_init
    action: on_init
    message_id: false
  - code: 109
    default: GROCERY/1.2.5/confirm/confirm/default.yaml
    action_id: confirm
    action: confirm
    message_id: true
  - code: 110
    default: GROCERY/1.2.5/on_confirm/on_confirm/default.yaml
    action_id: on_confirm
    action: on_confirm
    message_id: false
  - code: 1101
    default: GROCERY/1.2.5/on_status/on_status_accepted/default.yaml
    action_id: on_status_accepted
    action: on_status
    message_id: true
  - code: 111
    default: GROCERY/1.2.5/on_status/on_status_packed/default.yaml
    action_id: on_status_packed
    action: on_status
    message_id: true
  - code: 112
    default: GROCERY/1.2.5/on_status/on_status_agent_assigned/default.yaml
    action_id: on_status_agent_assigned
    action: on_status
    message_id: true
  - code: 113
    default: GROCERY/1.2.5/on_status/on_status_picked/default.yaml
    action_id: on_status_picked
    action: on_status
    message_id: true
  - code: 114
    default: GROCERY/1.2.5/on_status/on_status_out_for_delivery/default.yaml
    action_id: on_status_out_for_delivery
    action: on_status
    message_id: true
  - code: 115
    default: GROCERY/1.2.5/on_status/on_status_order_delivered/default.yaml
    action_id: on_status_order_delivered
    action: on_status
    message_id: true
  - code: 116
    default: GROCERY/1.2.5/track/track/default.yaml
    action_id: track
    action: track
    message_id: true
  - code: 117
    default: GROCERY/1.2.5/on_track/on_track/default.yaml
    action_id: on_track
    action: on_track
    message_id: false
  - code: 118
    default: GROCERY/1.2.5/on_search/on_search_118/default.yaml
    action_id: on_search_118
    action: on_search
    message_id: false
  - code: 119
    default: GROCERY/1.2.5/select/select_out_of_stock/default.yaml
    action_id: select_out_of_stock
    action: select
    message_id: true
  - code: 120
    default: GROCERY/1.2.5/on_select/on_select_out_of_stock/default.yaml
    action_id: on_select_out_of_stock
    action: on_select
    message_id: false
  - code: 121
    default: GROCERY/1.2.5/on_search/on_search_121/default.yaml
    action_id: on_search_121
    action: on_search
    message_id: false
  - code: 122
    default: GROCERY/1.2.5/select/select_122/default.yaml
    action_id: select_122
    action: select
    message_id: true
  - code: 123
    default: GROCERY/1.2.5/on_select/on_select_123/default.yaml
    action_id: on_select_123
    action: on_select
    message_id: false
  - code: 124
    default: GROCERY/1.2.5/init/init_124/default.yaml
    action_id: init_124
    action: init
    message_id: true
  - code: 125
    default: GROCERY/1.2.5/on_init/on_init_125/default.yaml
    action_id: on_init_125
    action: on_init
    message_id: false
  - code: 126
    default: GROCERY/1.2.5/confirm/confirm_126/default.yaml
    action_id: confirm_126
    action: confirm
    message_id: true
  - code: 127
    default: GROCERY/1.2.5/on_confirm/on_confirm_127/default.yaml
    action_id: on_confirm_127
    action: on_confirm
    message_id: false
  - code: 128
    default: GROCERY/1.2.5/cancel/cancel/default.yaml
    action_id: cancel
    action: cancel
    message_id: true
  - code: 129
    default: GROCERY/1.2.5/on_cancel/on_cancel/default.yaml
    action_id: on_cancel
    action: on_cancel
    message_id: false
  - code: 130
    default: GROCERY/1.2.5/on_select/on_select_130/default.yaml
    action_id: on_select_130
    action: on_select
    message_id: false
  - code: 131
    default: GROCERY/1.2.5/init/init_131/default.yaml
    action_id: init_131
    action: init
    message_id: true
  - code: 132
    default: GROCERY/1.2.5/on_init/on_init_132/default.yaml
    action_id: on_init_132
    action: on_init
    message_id: false
  - code: 133
    default: GROCERY/1.2.5/confirm/confirm_133/default.yaml
    action_id: confirm_133
    action: confirm
    message_id: true
  - code: 134
    default: GROCERY/1.2.5/on_confirm/on_confirm_134/default.yaml
    action_id: on_confirm_134
    action: on_confirm
    message_id: false
  - code: 135
    default: GROCERY/1.2.5/on_status/on_status_pending/default.yaml
    action_id: on_status_pending
    action: on_status
    message_id: true
  - code: 136
    default: GROCERY/1.2.5/on_status/on_status_packed_136/default.yaml
    action_id: on_status_packed_136
    action: on_status
    message_id: true
  - code: 137
    default: GROCERY/1.2.5/on_status/on_status_picked_137/default.yaml
    action_id: on_status_picked_137
    action: on_status
    message_id: true
  - code: 138
    default: GROCERY/1.2.5/on_status/on_status_out_for_delivery_138/default.yaml
    action_id: on_status_out_for_delivery_138
    action: on_status
    message_id: true
  - code: 139
    default: GROCERY/1.2.5/on_cancel/on_cancel_rto/default.yaml
    action_id: on_cancel_rto
    action: on_cancel
    message_id: false
  - code: 140
    default: GROCERY/1.2.5/on_status/on_status_rto_delivered/default.yaml
    action_id: on_status_rto_delivered
    action: on_status
    message_id: true
  - code: 141
    default: GROCERY/1.2.5/on_search/on_search_141/default.yaml
    action_id: on_search_141
    action: on_search
    message_id: false
  - code: 142
    default: GROCERY/1.2.5/select/select_142/default.yaml
    action_id: select_142
    action: select
    message_id: true
  - code: 143
    default: GROCERY/1.2.5/on_select/on_select_143/default.yaml
    action_id: on_select_143
    action: on_select
    message_id: false
  - code: 144
    default: GROCERY/1.2.5/init/init_144/default.yaml
    action_id: init_144
    action: init
    message_id: true
  - code: 145
    default: GROCERY/1.2.5/on_init/on_init_145/default.yaml
    action_id: on_init_145
    action: on_init
    message_id: false
  - code: 146
    default: GROCERY/1.2.5/confirm/confirm_146/default.yaml
    action_id: confirm_146
    action: confirm
    message_id: true
  - code: 147
    default: GROCERY/1.2.5/on_confirm/on_confirm_147/default.yaml
    action_id: on_confirm_147
    action: on_confirm
    message_id: false
  - code: 148
    default: GROCERY/1.2.5/on_update/on_update_part_cancel/default.yaml
    action_id: on_update_part_cancel
    action: on_update
    message_id: false
  - code: 149
    default: GROCERY/1.2.5/update/update_settlement_trail/default.yaml
    action_id: update_settlement_trail
    action: update
    message_id: true
  - code: 150
    default: GROCERY/1.2.5/on_status/on_status_pending_150/default.yaml
    action_id: on_status_pending_150
    action: on_status
    message_id: true
  - code: 151
    default: GROCERY/1.2.5/on_status/on_status_packed_151/default.yaml
    action_id: on_status_packed_151
    action: on_status
    message_id: true
  - code: 152
    default: GROCERY/1.2.5/on_status/on_status_picked_152/default.yaml
    action_id: on_status_picked_152
    action: on_status
    message_id: true
  - code: 153
    default: GROCERY/1.2.5/on_status/on_status_out_for_delivery_153/default.yaml
    action_id: on_status_out_for_delivery_153
    action: on_status
    message_id: true
  - code: 154
    default: GROCERY/1.2.5/on_status/on_status_order_delivered_154/default.yaml
    action_id: on_status_order_delivered_154
    action: on_status
    message_id: true
  - code: 155
    default: GROCERY/1.2.5/on_status/on_status_pending_155/default.yaml
    action_id: on_status_pending_155
    action: on_status
    message_id: true
  - code: 156
    default: GROCERY/1.2.5/on_status/on_status_packed_156/default.yaml
    action_id: on_status_packed_156
    action: on_status
    message_id: true
  - code: 157
    default: GROCERY/1.2.5/on_status/on_status_picked_157/default.yaml
    action_id: on_status_picked_157
    action: on_status
    message_id: true
  - code: 158
    default: GROCERY/1.2.5/on_status/on_status_out_for_delivery_158/default.yaml
    action_id: on_status_out_for_delivery_158
    action: on_status
    message_id: true
  - code: 159
    default: GROCERY/1.2.5/on_status/on_status_order_delivered_159/default.yaml
    action_id: on_status_order_delivered_159
    action: on_status
    message_id: true
  - code: 160
    default: GROCERY/1.2.5/update/update_liquidated/default.yaml
    action_id: update_liquidated
    action: update
    message_id: true
  - code: 161
    default: GROCERY/1.2.5/on_update/on_update_interim_liquidated/default.yaml
    action_id: on_update_interim_liquidated
    action: on_update
    message_id: false
  - code: 162
    default: GROCERY/1.2.5/on_update/on_update_liquidated/default.yaml
    action_id: on_update_liquidated
    action: on_update
    message_id: false
  - code: 163
    default: GROCERY/1.2.5/update/update_liquidated_settlement/default.yaml
    action_id: update_liquidated_settlement
    action: update
    message_id: true
  - code: 164
    default: GROCERY/1.2.5/update/update_reverse_qc/default.yaml
    action_id: update_reverse_qc
    action: update
    message_id: true
  - code: 165
    default: GROCERY/1.2.5/on_update/on_update_interim_reverseQc/default.yaml
    action_id: on_update_interim_reverseQc
    action: on_update
    message_id: false
  - code: 166
    default: GROCERY/1.2.5/on_update/on_update_approved/default.yaml
    action_id: on_update_approved
    action: on_update
    message_id: false
  - code: 167
    default: GROCERY/1.2.5/on_update/on_update_picked/default.yaml
    action_id: on_update_picked
    action: on_update
    message_id: false
  - code: 168
    default: GROCERY/1.2.5/update/update_reverse_qc_settlement/default.yaml
    action_id: update_reverse_qc_settlement
    action: update
    message_id: true
  - code: 169
    default: GROCERY/1.2.5/on_update/on_update_return_delivered/default.yaml
    action_id: on_update_return_delivered
    action: on_update
    message_id: false
  - code: 170
    default: GROCERY/1.2.5/on_update/on_update_interim_reverse_qc/default.yaml
    action_id: on_update_interim_reverse_qc
    action: on_update
    message_id: false
  - code: 171
    default: GROCERY/1.2.5/on_update/on_update_approval/default.yaml
    action_id: on_update_approval
    action: on_update
    message_id: false
  - code: 172
    default: GROCERY/1.2.5/on_update/on_update_picked_172/default.yaml
    action_id: on_update_picked_172
    action: on_update
    message_id: false
  - code: 173
    default: GROCERY/1.2.5/on_update/on_update_return_delivered_173/default.yaml
    action_id: on_update_return_delivered_173
    action: on_update
    message_id: false
  - code: 174
    default: GROCERY/1.2.5/on_update/on_update_interim_liquidated_174/default.yaml
    action_id: on_update_interim_liquidated_174
    action: on_update
    message_id: false
  - code: 175
    default: GROCERY/1.2.5/on_update/on_update_liquidated_175/default.yaml
    action_id: on_update_liquidated_175
    action: on_update
    message_id: false
  - code: 176
    default: GROCERY/1.2.5/update/update_return/default.yaml
    action_id: update_return
    action: update
    message_id: true
  - code: 177
    default: GROCERY/1.2.5/on_update/on_update_return_init/default.yaml
    action_id: on_update_return_init
    action: on_update
    message_id: false
  - code: 178
    action_id: on_update_return_approved
    default: GROCERY/1.2.5/on_update/on_update_return_approved/default.yaml
    action: on_update
    message_id: true
  - code: 179
    action_id: on_update_return_picked
    default: GROCERY/1.2.5/on_update/on_update_return_picked/default.yaml
    message_id: true
    action: on_update
  - code: 180
    action_id: on_search_inc_close
    default: GROCERY/1.2.5/on_search/on_search_inc_close/default.yaml
    action: on_search
    message_id: true
  - code: 181
    action_id: on_search_inc_open
    default: GROCERY/1.2.5/on_search/on_search_inc_open/default.yaml
    action: on_search
    message_id: true
  - code: 182
    action_id: init_cod
    default: GROCERY/1.2.5/init/init_cod/default.yaml
    action: init
    message_id: true
  - code: 183
    action_id: on_init_cod
    default: GROCERY/1.2.5/on_init/on_init_cod/default.yaml
    action: on_init
    message_id: false
  - code: 184
    action_id: confirm_cod
    default: GROCERY/1.2.5/confirm/confirm_cod/default.yaml
    action: confirm
    message_id: true
  - code: 185
    action_id: on_confirm_cod
    default: GROCERY/1.2.5/on_confirm/on_confirm_cod/default.yaml
    action: on_confirm
    message_id: false
  - code: 186
    action_id: on_status_order_delivered_cod
    default: GROCERY/1.2.5/on_status/on_status_order_delivered_cod/default.yaml
    action: on_status
    message_id: true
  - code: 187
    action_id: on_select_buyer_delivery
    default: GROCERY/1.2.5/on_select/on_select_buyer_delivery/default.yaml
    action: on_select
    message_id: false
  - code: 188
    action_id: init_buyer_delivery
    default: GROCERY/1.2.5/init/init_buyer_delivery/default.yaml
    action: init
    message_id: true
  - code: 189
    action_id: on_init_buyer_delivery
    default: GROCERY/1.2.5/on_init/on_init_buyer_delivery/default.yaml
    action: on_init
    message_id: false
  - code: 190
    action_id: on_status_ready_to_ship
    default: GROCERY/1.2.5/on_status/on_status_ready_to_ship/default.yaml
    action: on_status
    message_id: true
  - code: 191
    action_id: update_picked_up
    default: GROCERY/1.2.5/update/update_picked_up/default.yaml
    action: update
    message_id: true
  - code: 192
    action_id: update_delivered
    default: GROCERY/1.2.5/update/update_delivered/default.yaml
    action: update
    message_id: true
  - code: 193
    action_id: on_select_multi_fulfillment
    default: GROCERY/1.2.5/on_select/on_select_multi_fulfillment/default.yaml
    action: on_select
    message_id: false
  - code: 194
    action_id: init_multi_fulfillment
    default: GROCERY/1.2.5/init/init_multi_fulfillment/default.yaml
    action: init
    message_id: true
  - code: 195
    action_id: on_init_multi_fulfillment
    default: GROCERY/1.2.5/on_init/on_init_multi_fulfillment/default.yaml
    action: on_init
    message_id: false
